version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
       frontend:
          patterns:
            - "*"
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
       client:
          patterns:
            - "*"
